# --------------------------------------------------------------------------- #
#                                                                             #
#                               Three In A Row                                #
#                                                                             #
#                                  by Nikl                                    #
# --------------------------------------------------------------------------- #


# name of the language file (in the folder 'language')
#   'default' always uses the up-to-date english language file included in the plugin jar
#   To use your own language file or another language file from the folder, set 'langFile' to the name
#     of the file (including the extension)
langFile: "lang_hu.yml"

gameBox:
  mainButton:
    # define the Material and data for the button (format: 'material:data')
    materialData: "35:11"
    # display name of the button
    displayName: "&3Three In A Row"
    # lore of the button
    lore:
    - ""
    - "&1Japanese logic game"
  gameButtons:
    saveStats:
      materialData: "159:3"
      displayName: "&a&lThree In A Row"
      lore:
      - ""
      - "&3Check the &ltop list"
      - "&aGood luck!"
      - ""
      - "&1Cost: &420"
      - "&1Reward: &230"
      - "&1Token: &21"
      slot: 22
      cost: 20
      token: 1
      money: 30
      # option to display the items with the helping lore
      # that counts the blue and white tiles in the row/column
      #    default: true
      helpItems: true
      # if true the best score of this button is saved
      saveStats: true
  topListButtons:
    # use the same key as the game you want to display the top list for
    #   for that button 'saveStats' must be true (see above)
    saveStats:
      materialData: "159:11"
      displayName: "&a&lTop list"
      lore:
      - ""
      - "&cThreeInARow &1Top List"
      slot: 31
      # inventory title of the top list (%player% and %game%)
      inventoryTitle: '   &3Three In A Row&r Top List'
      # Lore of the skulls in the inventory. Use %rank% for the rank and %score% for the highest score of the player
      skullLore:
      - ''
      - '&6Rank:&1   %rank%'
      - '&6Solved:&1 %wins%'

rules:
  # enable/disable sound
  playSounds: true

# requires vault and an economy plugin
#   to enable economy do not forget to enable it for GameBox too
economy:
  enabled: false

game:
  blueTile:
    materialData: "35:11"
    displayName: "&1Blue tile"
  whiteTile:
    materialData: "35"
    displayName: "&rWhite tile"
  blueTileTip:
    materialData: "159:11"
    displayName: "&1Blue tile"
    lore:
    - ""
    - "&cThis cannot be changed"
  whiteTileTip:
    materialData: "159"
    displayName: "&rWhite tile"
    lore:
    - ""
    - "&cThis cannot be changed"
  wrongHelpItem:
    materialData: "160:14"
    displayName: "&4&lIncomplete:"
    lore:
    - ""
    - "Blue: %blue_count%/3"
    - "White: %white_count%/3"
  correctHelpItem:
    materialData: "160:13"
    displayName: "&a&lComplete!"
    lore:
    - ""
    - "Blue: 3/3"
    - "White: 3/3"
  backGround:
    materialData: "160:7"
    displayName: "&a"