#   The general configuration for the jobs plugin mostly includes how often the plugin
# saves user data (when the user is in the game), the storage method, whether
# to broadcast a message to the server when a user goes up a skill level.
#   It also allows admins to set the maximum number of jobs a player can have at
# any one time.

# Default language.
# Example: en, ru
# File in locale folder with same name should exist. Example: messages_ru.yml
locale-language: hu
# storage method, can be MySQL, sqlite
storage-method: sqlite
# Requires Mysql.
mysql-username: root
mysql-password: ''
mysql-hostname: localhost:3306
mysql-database: minecraft
mysql-table-prefix: jobs_
# How often in minutes you want it to save.  This must be a non-zero number
save-period: 10
# Should player data be saved on disconnect?
# Player data is always periodically auto-saved and autosaved during a clean shutdown.
# Only enable this if you have a multi-server setup, or have a really good reason for enabling this.
# Turning this on will decrease database performance.
save-on-disconnect: false
# Enable if you are using one data base for multiple servers across bungee network
# This will force to load players data every time he is logging in to have most up to date data instead of having preloaded data
# This will enable automaticaly save-on-disconnect feature
MultiServerCompatability: false
Optimizations:
  AutoJobJoin:
    # Use or not auto join jobs feature
    # If you are not using auto join feature, keep it disabled
    Use: false
    # Delay in seconds to perform auto join job if used after player joins server
    # If you using offline server, try to keep it slightly more than your login plugin gives time to enter password
    # For player to auto join job add permission node jobs.autojoin.[jobname]
    # Op players are ignored
    Delay: 15
  # With this set to true, offline player data will be taken from local player data files
  # This will eliminate small lag spikes when request is being send to mojangs servers for offline players data
  # Theroticali this should work without issues, but if you havving some, just disable
  # But then you can feal some small (100-200ms) lag spikes while performings some jobs commands
  UseLocalOfflinePlayersData: true
  DisabledWorlds:
    # By setting this to true, Jobs plugin will be disabled in given worlds
    # Only commands can be performed from disabled worlds with jobs.disabledworld.commands permission node
    Use: false
    List:
    - world
Logging:
  # With this set to true all players jobs actions will be logged to database for easy to see statistics
  # This is still in development and in feature it will expand
  Use: false
broadcast:
  on-skill-up:
    # Do all players get a message when somone goes up a skill level?
    use: false
  on-level-up:
    # Do all players get a message when somone goes up a level?
    use: false
    # For what levels you want to broadcast message? Keep it at 0 if you want for all of them
    levels:
    - 0
# Maximum number of jobs a player can join.
# Use 0 for no maximum
max-jobs: 2
# Hide jobs from player if they lack the permission to join the job
hide-jobs-without-permission: false
# Hide jobs info from player if they lack the permission to join the job
hide-jobsinfo-without-permission: false
# Option to allow payment to be made when killing mobs from a spawner
enable-pay-near-spawner: false
# enable-pay-near-spawner should be enabled for this to work
# 0.5 means that players will get only 50% exp/money from monsters spawned from spawner
pay-near-spawner-multiplier: 1.0
# VIP multiplier to pay for monsters from spawners, this will ignore global multiplier
# Use jobs.vipspawner permission node for this to be enabled
VIP-pay-near-spawner-multiplier: 1.0
# Option to allow payment to be made in creative mode
enable-pay-creative: false
# Option to allow payment to be made for exploring when player flyies
enable-pay-for-exploring-when-flying: false
# Adds the Jobs xp recieved to the player's Minecraft XP bar
add-xp-player: false
# Modifys chat to add chat titles.  If you're using a chat manager, you may add the tag {jobs} to your chat format and disable this.
modify-chat: false
modify-chat-prefix: '&c['
modify-chat-suffix: '&c]'
modify-chat-separator: ' '
# Do you want to use custom item/block/mob/enchant/color names
# With this set to true names like Stone:1 will be translated to Granite
# Name list is in TranslatableWords.yml file
UseCustomNames: true
# Changes how often, in seconds, players are paid out.  Default is 5 seconds.
# Setting this too low may cause tick lag.  Increase this to improve economy performance (at the cost of delays in payment)
economy-batch-delay: 10
# Enable async economy calls.
# Disable this if you have issues with payments or your plugin is not thread safe.
economy-async: true
Economy:
  # By disabling one of thies, players no longer will get particular payment.
  # Usefull for removing particular payment method without editing whole jobConfig file
  PaymentMethods:
    Money: true
    Points: false
    Exp: true
  MinimumOveralPayment:
    # Determines minimum payment. In example if player uses McMMO treefeller and earns only 20%, but at same time he gets 25% penalty from dynamic payment. He can 'get' negative amount of money
    # This will limit it to particular percentage
    # Works only when original payment is above 0
    use: false
    limit: 0.1
  MinimumOveralPoints:
    # Determines minimum payment. In example if player uses McMMO treefeller and earns only 20%, but at same time he gets 25% penalty from dynamic payment. He can 'get' negative amount of money
    # This will limit it to particular percentage
    # Works only when original payment is above 0
    use: false
    limit: 0.1
  DynamicPayment:
    # Do you want to use dinamic payment dependent on how many players already working for jobs
    # This can help automaticaly lift up payments for not so popular jobs and lower for most popular ones
    use: false
    equation: ((totalworkers / totaljobs) - jobstotalplayers)/10.0
    MaxPenalty: 25.0
    MaxBonus: 100.0
  # Server economy acount
  # With this enabled, players will get money from defined user (server account)
  # If this acount dont have enough money to pay for players for, player will get message
  UseServerAcount: false
  # Username should be with Correct capitalization
  AcountName: Server
  Taxes:
    # Do you want to use taxes feature for jobs payment
    use: true
    # Username should be with Correct capitalization, it can be same as settup in server account before
    AccountName: Server
    # Amount in percentage
    Amount: 10.0
    # Do you want to transfer taxes to server account
    TransferToServerAccount: false
    # With this true, taxes will be taken from players payment and he will get less money than its shown in jobs info
    # When its false player will get full payment and server account will get taxes amount to hes account
    TakeFromPlayersPayment: true
  Limit:
    # Money gain limit
    # With this enabled, players will be limited how much they can make in defined time
    # Time in seconds: 60 = 1min, 3600 = 1 hour, 86400 = 24 hours
    Money:
      Use: false
      # Do you want to stop money gain when exp limit reached?
      StopWithExp: false
      # Do you want to stop money gain when point limit reached?
      StopWithPoint: false
      # Equation to calculate max limit. Option to use totallevel to include players total amount levels of current jobs
      # You can always use simple number to set money limit
      # Default equation is: 500+500*(totallevel/100), this will add 1% from 500 for each level player have
      # So player with 2 jobs with level 15 and 22 will have 685 limit
      MoneyLimit: 500+500*(totallevel/100)
      # Time in seconds: 60 = 1min, 3600 = 1 hour, 86400 = 24 hours
      TimeLimit: 3600
      # Delay between announcements about reached money limit
      # Keep this from 30 to 5 min (300), as players can get annoyed of constant message displaying
      AnnouncmentDelay: 30
    # Point gain limit
    # With this enabled, players will be limited how much they can make in defined time
    Point:
      Use: false
      # Do you want to stop Point gain when exp limit reached?
      StopWithExp: false
      # Do you want to stop Point gain when money limit reached?
      StopWithMoney: false
      # Equation to calculate max limit. Option to use totallevel to include players total amount levels of current jobs
      # You can always use simple number to set limit
      # Default equation is: 500+500*(totallevel/100), this will add 1% from 500 for each level player have
      # So player with 2 jobs with level 15 and 22 will have 685 limit
      Limit: 500+500*(totallevel/100)
      # Time in seconds: 60 = 1min, 3600 = 1 hour, 86400 = 24 hours
      TimeLimit: 3600
      # Delay between announcements about reached limit
      # Keep this from 30 to 5 min (300), as players can get annoyed of constant message displaying
      AnnouncmentDelay: 30
    # Exp gain limit
    # With this enabled, players will be limited how much they can get in defined time
    # Time in seconds: 60 = 1min, 3600 = 1 hour, 86400 = 24 hours
    Exp:
      Use: false
      # Do you want to stop exp gain when money limit reached?
      StopWithMoney: false
      # Do you want to stop exp gain when point limit reached?
      StopWithPoint: false
      # Equation to calculate max money limit. Option to use totallevel to include players total amount of current jobs
      # You can always use simple number to set exp limit
      # Default equation is: 5000+5000*(totallevel/100), this will add 1% from 5000 for each level player have
      # So player with 2 jobs with level 15 and 22 will have 6850 limit
      Limit: 5000+5000*(totallevel/100)
      # Time in seconds: 60 = 1min, 3600 = 1 hour, 86400 = 24 hours
      TimeLimit: 3600
      # Delay between announcements about reached Exp limit
      # Keep this from 30 to 5 min (300), as players can get annoyed of constant message displaying
      AnnouncmentDelay: 30
  Repair:
    # Do you want to give money for only renaming items in anvil
    # Players will get full pay as they would for remairing two items when they only renaming one
    # This is not big issue, but if you want to disable it, you can
    PayForRenaming: true
  Crafting:
    # With this true, player will get money for all crafted items instead of each crafting action (like with old payment mechanic)
    # By default its false, as you can make ALOT of money if prices kept from old payment mechanics
    PayForEachCraft: false
  MilkingCow:
    # With this true, when timer is still going, cow milking event will be canceled
    # With this false, player will get bucket of milk, but still no payment
    CancelMilking: false
    # How ofter player can milk cows in seconds. Keep in mind that by default player can milk cow indefinetly and as often as he wants
    # Set to 0 if you want to disable timer
    Timer: 30
ExploitProtections:
  General:
    # Enable blocks protection, like ore, from exploiting by placing and destroying same block again and again.
    # This works only until server restart
    # Modify restrictedBlocks.yml for blocks you want to protect
    PlaceAndBreakProtection: false
    # Enable silk touch protection.
    # With this enabled players wont get paid for breaked blocks from restrictedblocks list with silk touch tool.
    SilkTouchProtection: false
    # Enable piston moving blocks from restrictedblocks list.
    # If piston moves block then it will be like new block and BlockPlaceAndBreakProtection wont work properly
    # If you using core protect and its being logging piston block moving, then you can disable this
    StopPistonBlockMove: false
    # Enable blocks timer protection.
    # Only enable if you want to protect block from beying broken to fast, useful for vegetables.
    # Modify restrictedBlocks.yml for blocks you want to protect
    BlocksTimer: false
    # All blocks will be protected X sec after player places it on ground.
    GlobalBlockTimer:
      use: false
      timer: 30
    # Do you want to pay when players pet kills monster/player
    # Can be exploited with mob farms
    # 0.2 means 20% of original reward
    # Optionaly you can give jobs.petpay permission node for specific players/ranks to get paid by VipPetPay multiplier
    PetPay: 0.1
    VipPetPay: 1.0
  # McMMO abilities
  McMMO:
    # Players will get part of money from cutting trees with treefeller ability enabled.
    # 0.2 means 20% of original price
    TreeFellerMultiplier: 0.2
    # Players will get part of money from braking blocks with gigaDrill ability enabled.
    # 0.2 means 20% of original price
    gigaDrillMultiplier: 0.2
    # Players will get part of money from braking blocks with super breaker ability enabled.
    # 0.2 means 20% of original price
    superBreakerMultiplier: 0.2
  # MythicMobs plugin support
  # Disable if you having issues with it or using old version
  MythicMobs:
    enabled: true
  Spawner:
    # Prevent slime spliting when they are from spawner
    # Protects agains exploiting as new splited slimes is treated as naturaly spawned and not from spawner
    PreventSlimeSplit: true
    # Prevent magmacube spliting when they are from spawner
    PreventMagmaCubeSplit: true
  # Prevent water braking placed blocks. Protection resets with server restart or after plants grows to next stage with bone powder or naturally
  # For strange reason works only 5 of 10 times, but this is completely enough to prevent exploiting
  WaterBlockBreake: false
# Breeder finder.
# If you are not using breeding payment, you can disable this to save little resources. Really little.
use-breeder-finder: true
# Money exp boost with special permision.
# You will need to add special permision for groups or players to have money/exp/points boost.
# Use: jobs.boost.[jobname].money or jobs.boost.[jobname].exp or jobs.boost.[jobname].points or jobs.boost.[jobname].all for all of them with specific jobs name.
# Use: jobs.boost.all.money or jobs.boost.all.exp or jobs.boost.all.points or jobs.boost.all.all to get boost for all jobs
# 1.25 means that player will get 25% more than others, you can set less than 1 to get less from anothers
boost:
  exp: 1.5
  money: 1.5
  points: 1.5
# Old job save
# Players can leave job and return later with some level loss during that
# You can fix players level if hes job level is at max level
old-job:
  level-loss-percentage: 30
  fix-at-max-level: true
ActionBars:
  Messages:
    # When this set to true player will see action bar messages by default
    EnabledByDefault: true
BossBar:
  # Enables BossBar feature
  # Works only from 1.9 mc version
  Enabled: true
  Messages:
    # When this set to true player will see Bossbar messages by default
    EnabledByDefault: true
  # If enabled boss bar will update after each action
  # If disabled, BossBar will update only on each payment. This can save some server resources
  ShowOnEachAction: false
  # How long in sec to show BossBar for player
  # If you have disabled ShowOnEachAction, then keep this number higher than payment interval for better experience
  Timer: 6
# You can enable/disable message shown for players in action bar
ShowActionBars:
  OnTitleChange: false
  OnLevelChange: false
  OnEmptyServerAcount: false
# Chat messages
# You can enable/disable message shown for players in chat
ShowChatMessage:
  OnTitleChange: false
  OnLevelChange: false
  OnEmptyServerAcount: false
# Sounds
# Extra sounds on some events
# All sounds can be found in https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
Sounds:
  LevelUp:
    use: true
    sound: ENTITY_PLAYER_LEVELUP
    volume: 1
    pitch: 3
  TitleChange:
    use: true
    sound: ENTITY_PLAYER_LEVELUP
    volume: 1
    pitch: 3
# You can disable this to save SMALL amount of server resources
Signs:
  Enable: false
  Colors:
    ColorizeJobName: false
  # This is update for same job signs, to avoid huge lag if you have bunch of same type signs. Keep it from 1 to as many sec you want
  InfoUpdateInterval: 5
Scoreboard:
  # This will enables to show top list in scoreboard instead of chat
  ShowToplist: true
  # For how long to show scoreboard
  interval: 10
JobsBrowse:
  # Do you want to show total amount of workers for job in jobs browse window
  ShowTotalWorkers: true
  # Do you want to show GUI when performing /jobs join command
  ShowPenaltyBonus: true
JobsGUI:
  # Do you want to show GUI when performing /jobs browse command
  OpenOnBrowse: true
  # Do you want to show chat information when performing /jobs browse command
  ShowChatBrowse: false
  # With true left mouse button will join job and right will show more info
  # With false left mouse button will show more info, rigth will join job
  # Dont forget to adjust locale file
  SwitcheButtons: false
  OpenOnJoin: true
Schedule:
  Boost:
    # Do you want to enable scheduler for global boost
    Enable: false
